#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <filesystem>

int main(int argc, char* argv[]) {
    std::cout << "// file generated by file2byte - created by ellii\n\n";

    if (argc < 2) {
        std::cerr << "usage: drag a file onto this executable to convert it.\n";
        return 1;
    }

    std::string inputPath = argv[1];
    std::filesystem::path inFile(inputPath);
    std::string fileName = inFile.filename().string();

    std::ifstream file(inputPath, std::ios::binary);
    if (!file) {
        std::cerr << "error: Cannot open file '" << inputPath << "'\n";
        return 1;
    }

    std::vector<unsigned char> bytes((std::istreambuf_iterator<char>(file)),
                                     std::istreambuf_iterator<char>());
    file.close();

    std::string outName = inFile.stem().string() + "_bytes.h";
    std::ofstream outFile(outName);
    if (!outFile) {
        std::cerr << "error: Cannot create output file '" << outName << "'\n";
        return 1;
    }

    outFile << "// file generated by file2byte - created by ellii\n";
    outFile << "// thx for using file2byte <3\n";
    outFile << "#include <cstddef>\n\n";

    std::string varName = inFile.stem().string();
    for (auto &c : varName)
        if (!std::isalnum(static_cast<unsigned char>(c))) c = '_';
    
    std::string fileType = inFile.extension().string();
    if (!fileType.empty() && fileType[0] == '.') fileType.erase(0, 1);

    outFile << "const unsigned char " << varName << "_data[] = {\n    ";

    for (size_t i = 0; i < bytes.size(); ++i) {
        outFile << "0x" << std::hex << std::uppercase
                << (int)bytes[i];
        if (i != bytes.size() - 1) outFile << ", ";
        if ((i + 1) % 12 == 0) outFile << "\n    ";
    }

    outFile << std::dec << "\n};\n";

    outFile << "const size_t " << varName << "_size = sizeof(" << varName << "_data);\n";

    outFile << "const char* " << varName << "_type = \"" << fileType << "\";\n";

    outFile.close();

    std::cout << "success thanks for using elli's tools <3 " << "\n";
    return 0;
}

