#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include <filesystem>
#include <cctype>
#include <algorithm>

int main(int argc, char* argv[]) {
    std::cout << "// file generated by file2byte restore - ellii\n\n";

    if (argc < 2) {
        std::cerr << "usage: drag a _bytes.h file onto this program to restore the original file.\n";
        return 1;
    }

    std::string inputPath = argv[1];
    std::filesystem::path inFile(inputPath);

    std::ifstream cppFile(inputPath);
    if (!cppFile) {
        std::cerr << "error: cannot open file '" << inputPath << "'\n";
        return 1;
    }

    std::string content((std::istreambuf_iterator<char>(cppFile)),
                        std::istreambuf_iterator<char>());
    cppFile.close();

    size_t namePos = content.find("const unsigned char ");
    if (namePos == std::string::npos) {
        std::cerr << "error: no valid byte array found.\n";
        return 1;
    }
    namePos += std::string("const unsigned char ").size();

    size_t nameEnd = content.find("_data", namePos);
    if (nameEnd == std::string::npos) {
        std::cerr << "error: could not find variable name.\n";
        return 1;
    }

    std::string varName = content.substr(namePos, nameEnd - namePos);
    std::transform(varName.begin(), varName.end(), varName.begin(),
                   [](unsigned char c){ return std::tolower(c); });

    std::string typeToken = varName + "_type = \"";
    size_t typePos = content.find(typeToken);
    std::string fileType = "bin";
    if (typePos != std::string::npos) {
        typePos += typeToken.size();
        size_t typeEnd = content.find('"', typePos);
        if (typeEnd != std::string::npos) {
            fileType = content.substr(typePos, typeEnd - typePos);
        }
    }

    size_t braceStart = content.find('{', nameEnd);
    size_t braceEnd = content.find('}', braceStart);
    if (braceStart == std::string::npos || braceEnd == std::string::npos) {
        std::cerr << "error: could not parse byte array contents.\n";
        return 1;
    }

    std::string arrayData = content.substr(braceStart + 1, braceEnd - braceStart - 1);

    std::vector<unsigned char> bytes;
    std::istringstream ss(arrayData);
    std::string token;
    while (std::getline(ss, token, ',')) {
        token.erase(remove_if(token.begin(), token.end(), ::isspace), token.end());
        if (token.rfind("0x", 0) == 0) {
            unsigned int byteVal;
            std::stringstream hexByte(token);
            hexByte >> std::hex >> byteVal;
            bytes.push_back(static_cast<unsigned char>(byteVal));
        }
    }

    if (bytes.empty()) {
        std::cerr << "error: no bytes parsed from file.\n";
        return 1;
    }

    std::string outName = varName + "_restored." + fileType;
    std::ofstream outFile(outName, std::ios::binary);
    if (!outFile) {
        std::cerr << "error: cannot create output file '" << outName << "'\n";
        return 1;
    }

    outFile.write(reinterpret_cast<const char*>(bytes.data()), bytes.size());
    outFile.close();

    std::cout << "successfully restored file: " << outName
              << " (" << bytes.size() << " bytes)\n";
    return 0;
}
